/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: '#0a0e27',
        surface: 'rgba(232, 224, 208, 0.05)',
        'surface-raised': '#111533',
        overlay: 'rgba(17, 21, 51, 0.95)',
        'text-primary': '#e8e0d0',
        'text-secondary': '#8b83a0',
        'text-muted': '#a098c0',
        'text-verse': '#6b6380',
        'row-time': '#b0a8c0',
        accent: {
          DEFAULT: '#d4a843',
          hover: '#c49430',
          glow: 'rgba(212, 168, 67, 0.4)',
        },
        border: 'rgba(232, 224, 208, 0.1)',
        placeholder: '#7a7390',
        'toast-bg': 'rgba(17, 21, 51, 0.95)',
      },
      fontFamily: {
        arabic: ['Noto Naskh Arabic', 'serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
      },
      spacing: {
        '0.5': '0.125rem',
        '1': '0.25rem',
        '1.5': '0.375rem',
        '2': '0.5rem',
        '2.5': '0.625rem',
        '3': '0.75rem',
        '3.5': '0.875rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
      },
      borderRadius: {
        DEFAULT: '6px',
        sm: '4px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        '2xl': '22px',
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'pulse-soft': 'pulse 2s ease-in-out infinite',
        'float': 'particleFloat 5s linear infinite',
        'timer-bg': 'timerBgShift 10s ease-in-out infinite alternate',
        'ornament-pulse': 'ornamentPulse 2s ease-in-out infinite',
      },
      keyframes: {
        particleFloat: {
          '0%': { transform: 'translateY(0) translateX(0)', opacity: '0' },
          '15%': { opacity: '0.8' },
          '70%': { opacity: '0.5' },
          '100%': { transform: 'translateY(-80px) translateX(20px)', opacity: '0' },
        },
        timerBgShift: {
          '0%': { transform: 'scale(1) rotate(0deg)' },
          '100%': { transform: 'scale(1.05) rotate(2deg)' },
        },
        ornamentPulse: {
          '0%, 100%': { opacity: '0.3' },
          '50%': { opacity: '0.7' },
        },
      },
    },
  },
  plugins: [],
};
